### ISSUE TITLE
Linking to software versions

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/FreqFun#3]
Gang, we've been pretty lax in the notebooks so far about specifying with which versions of the software each notebook was built. We need two things:

1.  From now on, each notebook needs to document the version of Pyleoclim (and any other relevant code) required to execute it. 

1.  we need to go make existing notebooks v0.5.0 compatible.

**Comment by khider** [comment]
We switch to a model with an environment.yml file. Each release would have the complete environment needed to run the notebooks.
